### ISSUE TITLE
Attribution for node-ecdsa-sig-formatter

### ISSUE THREAD

**Issue by waikilee** [blockstack/jsontokens-js#11]
Hi, 

We've noticed that you're making use of code from https://github.com/Brightspace/node-ecdsa-sig-formatter.  We're happy you were able to make use of this code which itself is open source and licensed under Apache for others to use and build upon for free.  However, as part of the terms of the Apache license, we would really appreciate it if you could give us appropriate attribution for our work.

Here is a generic sample NOTICE file you can include: https://www.apache.org/licenses/example-NOTICE.txt

Here is a sample statement that would work for this.
"This product includes software developed by D2L Corporation (https://github.com/Brightspace/node-ecdsa-sig-formatter)"

Thanks!

**Comment by kantai** [comment]
Hi @waikilee -- we added a notice to the source code in question:

https://github.com/blockstack/jsontokens-js/blob/master/src/cryptoClients/ecdsaSigFormatter.js#L2

**Comment by waikilee** [comment]
Thank you! We appreciate it.  Happy coding.
