### ISSUE TITLE
Remove deprecated dependency

### ISSUE THREAD

**Issue by timkinnane** [blockstack/jsontokens-js#13]
https://github.com/blockstack/jsontokens-js/blob/0e3620a47553651802e20fd8f432fc1b7d3d7bea/package.json#L53

Crypto is deprecated. As per blockstack.js issues: 
- https://github.com/blockstack/blockstack.js/issues/308
- https://github.com/blockstack/blockstack.js/issues/305

Having it in the package manifest here means that (in Meteor at least), when it's required in `blockstack.js` it will find the version in `node_modules` instead of the core Node module. The outcome is a failed import and `Cannot find module 'crytpo'` error.

The only way to avoid this seems to be making sure it's not required by any dependency in the app.
I have recompiled and run tests and everything seems to function fine just using Node’s core `crypto` module.

My problem and solution was similar to another app which illustrates the thought process better: https://github.com/ccxt/ccxt/issues/23

**Comment by meteorplus** [comment]
please @jackzampolin  update that package.json file it's a simple change but has a huge impact on other packages!!!

thank you
