### ISSUE TITLE
What hashing algorithms can be used?

### ISSUE THREAD

**Issue by TechyTimo** [blockstack/jsontokens-js#18]
I see in the example you are signing one with "ES256k" 
`
token = new TokenSigner('ES256', rawPrivateKey).sign(tokenPayload)`

and decoding another that was signed with "ES256".
```

console.log(tokenData)
{ header: { alg: 'ES256', typ: 'JWT' }, ...
```

But when I try to sign with "ES256" I get the error "invalid signing algorithm".

What hashing algorithms can be used?

**Comment by vsund** [comment]
I think you're talking about an old state of the readme, currently I don't see a `ES236` in the example code.

As of my understanding the library is only capable of signing/verifying with `ES235K` (also note that this is curve secp256k1 which is not in the JWT standard).
