### ISSUE TITLE
Add hint to readme that only non-standard es256k is supported

### ISSUE THREAD

**Issue by vsund** [blockstack/jsontokens-js#23]
If I understood this correctly, this library only supports es256k (or curve secp256k1), which isn't a JWT standard curve.
I think the readme should state that in a prominent manner :)

Edit: Can raise a PR for this when it's confirmed.

**Comment by trailofdad** [comment]
I spent too much time learning this the hard way 😕 . Should definitely make this clear on both your github and NPM page.

**Comment by kantai** [comment]
I added a note on the README.md for this -- this will update on npm on the next release. Thanks for raising this issue.
