### ISSUE TITLE
Update Base64Url dep to latest version to fix `Out-of-bounds Read` Security Issue

### ISSUE THREAD

**Issue by MichaelFedora** [blockstack/jsontokens-js#28]
NPM gives off an audit warning because this library uses Base64Url `^2.0.0`, which contains the Out-of-bounds read security issue. This issue seems to be patched in the `^3.0.0` version of the Base64Url library.

Source: https://nodesecurity.io/advisories/658

**Comment by kantai** [comment]
Thanks for letting us know @MichaelFedora -- will look into updating (or possibly eliminating the dependency) now.
