### ISSUE TITLE
`TokenVerifier.verify` function does not check expiration time

### ISSUE THREAD

**Issue by aviggiano** [blockstack/jsontokens-js#32]
Please see the test below:

```javascript
const { TokenSigner, TokenVerifier } = require('jsontokens-js')

const rawPrivateKey = '278a5de700e29faae8e40e366ec5012b5ec63d36ec77e8a2417154cc1d25383f'
const tokenPayload = { iat: 1440713414.85, exp: 1340713414.85 } // clearly expired
const token = new TokenSigner('ES256K', rawPrivateKey).sign(tokenPayload)

const rawPublicKey = '03fdd57adec3d438ea237fe46b33ee1e016eda6b585c3e27ea66686c2ea5358479'
const verified = new TokenVerifier('ES256K', rawPublicKey).verify(token)

console.log({verified}) 
// logs { verified: true }, but I was expecting { verified: false } 
```

Indeed, the [`verifyCompact`](https://github.com/blockstack/jsontokens-js/blob/master/src/verifier.js#L35) function seems to only care about the signature of the token, and not about the expiration timeout.

Please advise, as this seems like a big security flaw.

**Comment by kantai** [comment]
Hi @aviggiano -- that's correct, but many JWT libraries behave this way -- see the "EXP check" field in the comparison tables here:

https://jwt.io/

The reason we don't validate the `exp` field is that different consumers of this library will not necessarily share the same definition, use, and expected behavior for the `exp` field.

**Comment by aviggiano** [comment]
Hey @kantai

Thank you for the prompt response.

If that's the expected behavior, that's ok. 
I guess I just assumed this lib would validate the expiration field by default. 

Maybe it's worth adding a note on the README or on the method documentation to warn people like me.

**Comment by kantai** [comment]
Updated the README, thanks for the suggestion @aviggiano!
