### ISSUE TITLE
TokenInterface is Mis-Typed

### ISSUE THREAD

**Issue by MichaelFedora** [blockstack/jsontokens-js#39]
Within [decode.ts](https://github.com/blockstack/jsontokens-js/blob/master/src/decode.ts), it is as following:

```typescript
export interface TokenInterface {
    header: any[];
    payload: any;
    signature: any;
}
```

**Header should be at least of `any` type and *not* `any[]`**. That's because Headers generally are `{ alg: string, typ: string }`, and are quite honestly never an array.

Also, you can make it a bit better by adding typings for fields that may or may not be there, like so:

```typescript
export interface TokenInterface {
    header: {
      [key: string]: any;
      alg?: string;
      typ?: string;
    };
    payload: {
      [key: string]: any;
      iss?: string;
      jti?: string;
      iat?: string | number;
      exp?: string | number;
    };
    signature: string;
}
```

But that's up to you.

**Comment by zone117x** [comment]
Thanks @MichaelFedora! Just PR'd with your suggested changes https://github.com/blockstack/jsontokens-js/pull/40
